language: node_js
node_js:
    - "node"
    - "8"
env:
    global:
        - USER=monumentjs
        - REPO=monumentjs.github.io
        - GITHUB_REPO="github.com/${USER}/${REPO}.git"
script:
    - "npm run lint"
    - "npm run compile"
    - "npm install"
    - "npm test"
after_success:
    # Publish docs
    - "npm run docs"
    - "git config user.email achugaev93@gmail.com"
    - "git config user.name \"Alex Chugaev\""
    - "git clone https://github.com/monumentjs/monumentjs.github.io.git"
    - "cd monumentjs.github.io"
    - "rm -rf ./docs"
    - "mv ../docs ./docs"
    - "git add ."
    - "git commit -m \"updated source code documentation\""
    - "git push \"https://${GITHUB_TOKEN}@${GITHUB_REPO}\" master"
os:
    - "linux"
    - "osx"
notifications:
    slack: monumentjs:gkkM1IAYfH4A2eP4ZB6FXGQ3
