language: node_js
node_js:
  - "node"
  - "6"
before_install:
  - "npm --version"
script:
  - "npm run lint"
  - "npm run compile"
  - "npm run test:coverage"
after_script:
  - "npm run coveralls"
os:
  - "linux"
  - "osx"
