language: node_js
node_js:
  - 'node'
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
env:
  global:
    - ORG_NAME=monumentjs
    - SITE_REPO_NAME=monumentjs.github.io
    - GITHUB_SITE_REPO="github.com/${ORG_NAME}/${SITE_REPO_NAME}.git"
script:
  - 'npm run lint'
  - 'npm run compile'
  - 'npm install'
  - 'npm test'
after_success:
  # Publish coverage
  - 'npm run coveralls'
  # Publish docs
  - 'npm run docs'
  - 'git config user.email ${GIT_USER_EMAIL}'
  - 'git config user.name "${GIT_USER_NAME}"'
  - 'git clone https://${GITHUB_SITE_REPO}'
  - 'cd ${SITE_REPO_NAME}'
  - 'rm -rf ./package'
  - 'mv ../package ./package'
  - 'git add .'
  - 'git commit -m "updated api reference"'
  - 'git push "https://${GITHUB_TOKEN}@${GITHUB_SITE_REPO}" master'
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: script
  on:
    node: 'node'
    branch: master
    tags: true
  skip_cleanup: true
  script: 'npm run lerna:publish'
os:
  - 'linux'
  - 'osx'
notifications:
  slack: monumentjs:gkkM1IAYfH4A2eP4ZB6FXGQ3
