language: node_js
node_js:
  - "node"
  - "6"
  - "5"
before_install:
  - "yarn global add typescript tslint jest-cli"
  - "yarn --version"
  - "tsc --version"
  - "tslint --version"
  - "jest --version"
script:
  - "tslint --format stylish --project ."
  - "tsc"
  - "jest"
os:
  - "linux"
  - "osx"
