language: node_js
node_js:
  - "node"
  - "8"
install:
  - "npm i -g npm"      # install latest NPM
script:
  - "npm run lint"      # lint TypeScript sources
  - "npm run compile"   # compile TypeScript sources
  - "npm install"       # build dependencies graph with Lerna
  - "npm test"          # run tests
os:
  - "linux"
  - "osx"
