language: node_js
node_js:
    - "node"
    - "8"
env:
    global:
        - ORG_NAME=monumentjs
        - SITE_REPO_NAME=monumentjs.github.io
        - GITHUB_SITE_REPO="github.com/${ORG_NAME}/${SITE_REPO_NAME}.git"
script:
    - "npm run lint"
    - "npm run compile"
    - "npm install"
    - "npm test"
after_success:
    # Publish coverage
    - "npm run coveralls"
    # Publish docs
    - "npm run docs"
    - "git config user.email achugaev93@gmail.com"
    - "git config user.name \"Alex Chugaev\""
    - "git clone https://${GITHUB_SITE_REPO}"
    - "cd ${SITE_REPO_NAME}"
    - "rm -rf ./api"
    - "mv ../api ./api"
    - "git add ."
    - "git commit -m \"updated api reference\""
    - "git push \"https://${GITHUB_TOKEN}@${GITHUB_SITE_REPO}\" master"
os:
    - "linux"
    - "osx"
notifications:
    slack: monumentjs:gkkM1IAYfH4A2eP4ZB6FXGQ3
