language: node_js
node_js:
  - "node"
  - "6"
before_install:
  - "yarn global add typescript tslint jest-cli"
  - "yarn --version"
  - "tsc --version"
  - "tslint --version"
  - "jest --version"
script:
  - "yarn run lint"
  - "yarn run compile"
  - "yarn run test"
os:
  - "linux"
  - "osx"
